config/routes.rb
Rails.application.routes.draw do
  get 'application/infos'
  get 'application/contact'
  get 'application/rules'
  get 'stats', to: 'stats#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: [:new, :create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: [:index, :show]
  resources :regions, only: [:index]
  resources :tags, only: [:index, :show]
  resources :maps, only: [:index]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/models/orga.rb
# Groups related to this agenda
class Orga < ActiveRecord::Base
  has_paper_trail

  belongs_to :region
  belongs_to :kind

  validates :kind, presence: true
  validates :name, presence: true
  validates :region, presence: true
  validates :url, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :feed, allow_blank: true, format: %r{\Ahttps?:\/\/.*\..*\z}
  validates :contact, presence: true, email: true
  validates :submitter, allow_blank: true, email: true

  scope :moderated, -> { where moderated: true }
  scope :unmoderated, -> { where moderated: false }

  before_validation do
    self.secret ||= SecureRandom.urlsafe_base64(32)[0...32]
    self.submission_time ||= Time.zone.now

    # Populate submitter using contact info if absent
    self.submitter = contact if submitter.blank?
  end

  after_create do
    send_secret
  end

  after_update do
    send_secret if secret_changed?

    if moderated_changed?
      OrgaMailer.accept(self).deliver_now!
    else
      OrgaMailer.update(self).deliver_now!
    end
  end

  before_destroy do
    OrgaMailer.destroy(self).deliver_now!
  end

  def send_secret
    OrgaMailer.create(self).deliver_now!
  end

  def name_as_tag
    name.gsub(/[\s\*']/, '-').delete ':'
  end
end

app/controllers/orgas_controller.rb
# Groups life cycle
class OrgasController < ApplicationController
  before_action :set_orga, except: [:index, :new, :create]
  before_action :set_mailer_host
  before_action :authenticate_user!, only: [:edit, :update, :cancel, :destroy],
                                     unless: :check_secret
  before_action :authenticate_user!, only: [:validate, :accept]

  def index
    @search = Orga.moderated.search params[:q]
    @search.sorts = 'name' if @search.sorts.empty?
    @orgas = @search.result.page params[:page]
  end

  # GET /orgas/new
  def new
    @orga = Orga.new
  end

  # POST /orgas
  # POST /orgas.json
  def create
    @orga = Orga.new orga_params
    respond_to do |format|
      if @orga.save
        format.html { redirect_to :root, notice: t('.ok') }
        # 201 means :created
        format.json { render action: 'show', status: 201, location: @orga }
      else
        format.html { render action: 'new' }
        # 422 means :unprocessable_entity
        format.json { render json: @orga.errors, status: 422 }
      end
    end
  end

  def show
    @search = Orga.search params[:q]

    @events_future = Event.moderated.future.tag @orga.name_as_tag
    @events_past = Event.moderated.past.tag @orga.name_as_tag
  end

  # PATCH/PUT /orgas/1
  # PATCH/PUT /orgas/1.json
  def update
    respond_to do |format|
      if @orga.update orga_params
        format.html { redirect_to @orga, notice: t('.ok') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # 422 means :unprocessable_entity
        format.json { render json: @orga.errors, status: 422 }
      end
    end
  end

  # PATCH/PUT /accept/1
  # PATCH/PUT /accept/1.json
  def accept
    @orga.update moderated: true
    respond_to do |format|
      format.html { redirect_to :orgas, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  # DELETE /orgas/1
  # DELETE /orgas/1.json
  def destroy
    @orga.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: t('.ok') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_orga
    @orga = Orga.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through
  def orga_params
    params.require(:orga)
      .permit :lock_version, :kind_id, :name, :city, :department, :region_id,
              :url, :feed, :contact, :submitter
  end

  # Check that you can only edit an existing event if you know its secret
  def check_secret
    !@orga.secret || @orga.secret == params[:secret]
  end
end

app/helpers/orgas_helper.rb
# Helper for the orga views
module OrgasHelper
  def set_orga_meta
    set_meta_tags \
      description: @orga.url,
      DC: { title: @orga.name },
      geo: {
        region: @orga.region,
        placename: @orga.city,
        position: "#{@orga.city.try :latitude}; #{@orga.city.try :longitude}"
      }
  end
end

app/views/orgas/_form.html.haml
= form_for @orga do |f|
  - if @orga.persisted?
    = hidden_field_tag :secret, params[:secret]

  - if @orga.errors.any?
    #flash_messages
      - @orga.errors.full_messages.each do |msg|
        %p.flash.alert= msg

  .field.kind
    = f.label :kind
    %span.radios
      - Kind.all.each do |kind|
        = f.radio_button :kind_id, kind.id
        = f.label "kind_id_#{kind.id}" do
          %em.fa{ class: "fa-#{kind.icon}" }
          = Kind.human_attribute_name "name_#{kind.name}"
  .field.name
    = f.label :name
    = f.text_field :name, required: true
  .field.city
    = f.label :city
    = f.text_field :city, list: :cities
    %datalist#cities
      - Event.group(:city).order('count(city) desc').pluck(:city).each do |city|
        %option= city
  .field.department
    = f.label :department
    = f.text_field :department
  .field.region
    = f.label :region
    = f.collection_select :region_id, Region.all, :id, :name

  .field.url
    .helper
      :markdown
        #{t '.url_helper'}
    = f.label :url
    = f.url_field :url, placeholder: 'Ex: http://april.org'
  .field.feed
    .helper
      :markdown
        #{t '.feed_helper'}
    = f.label :feed
    = f.url_field :feed, placeholder: 'Ex: http://april.org/index.rss'
  .field.contact
    .helper
      :markdown
        #{t '.contact_helper'}
    = f.label :contact
    = f.email_field :contact
  .field.submitter
    .helper
      :markdown
        #{t '.submitter_helper'}
    = f.label :submitter
    = f.email_field :submitter

  .actions
    = f.button do
      %em.fa.fa-check
      = t '.save'

app/views/orgas/_search.html.haml
= search_form_for @search || Orga.search(params[:q]) do |f|
  = f.label :search, t('.label')
  %em.fa.fa-users
  = f.search_field :name_or_city_or_department_or_region_name_or_url_cont,
    id: :q_search, size: 16,
    placeholder: t('.title', entity: Orga.model_name.human)
  = f.button class: :search do
    %em.fa.fa-search
    %span.label= t '.label'

app/views/orgas/cancel.html.haml
%h2
  %em.fa.fa-trash-o
  = t '.title'

- if @orga.moderated?
  %h3.warning= t '.already_moderated'

%fieldset
  = form_for @orga, method: :delete do |f|
    = hidden_field_tag :secret, params[:secret]
    %h2= t '.confirm'

    = f.submit t('.ok'), name: :yes
    = link_to t('.ko'), @orga, class: :button

%fieldset
  %legend= Orga.model_name.human
  = render file: '/orgas/show'

app/views/orgas/edit.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

%fieldset
  %legend
    %em.fa.fa-pencil
    = t '.edit'
  = render 'form'

app/views/orgas/index.html.haml
%h2
  %em.fa.fa-users
  = title t 'orgas.search.title', entity: Orga.model_name.human

= render 'search'

%table.list.autopagerize_page_element
  %thead
    %th= sort_link @search, :kind_name, Orga.human_attribute_name(:kind)
    %th= sort_link @search, :name
    %th= sort_link @search, :city
    %th= sort_link @search, :department
    %th= sort_link @search, :region_name, Orga.human_attribute_name(:region)
    %th= sort_link @search, :url
    %th/

  %tbody
    - @orgas.each do |orga|
      %tr
        %td
          - if orga.kind
            %em.fa{ class: "fa-#{orga.kind.icon}",
              title: Kind.human_attribute_name("name_#{orga.kind.name}") }
        %td
          = orga.name
          - if orga.url =~ /^http/
            = image_tag orga.url + '/favicon.ico', alt: '', class: :favicon
        %td= orga.city
        %td= orga.department
        %td= orga.region
        %td= link_to orga.url, orga.url
        %td
          = link_to t('show'),
            orga_path(orga, q: params[:q], page: params[:page]),
            class: :view_link

= paginate @orgas

= link_to new_orga_path do
  %em.fa.fa-plus
  = t '.new'

app/views/orgas/new.html.haml
%h2
  %em.fa.fa-users
  = title t '.title'

%fieldset
  %legend
    %em.fa.fa-pencil
    = t '.edit'
  = render 'form'

app/views/orgas/show.html.haml
- set_orga_meta

%h2
  - if @orga.kind
    %em.fa{ class: "fa-#{@orga.kind.icon}",
      title: Kind.human_attribute_name("name_#{@orga.kind.name}") }
  = title @orga.name
  = image_tag @orga.url + '/favicon.ico', alt: '', class: :favicon

- if controller.controller_name == 'orgas' && controller.action_name == 'show'
  %aside
    %h1
      %em.fa.fa-link
      = t '.links'

    %ul.fa-ul
      %li
        = link_to orgas_path(q: params[:q], page: params[:page]),
          class: :back do
          %em.fa.fa-li.fa-arrow-left
          = Orga.model_name.human.pluralize
      %li
        = link_to events_path tag: @orga.name do
          %em.fa.fa-li.fa-calendar
          Agenda

      %li
        = link_to events_path format: :rss, tag: @orga.name do
          %em.fa.fa-li.fa-rss
          RSS

      %li
        = link_to events_path format: :ics, tag: @orga.name do
          %em.fa.fa-li.fa-th-list
          iCal

      %li
        = link_to maps_path tag: @orga.name do
          %em.fa.fa-li.fa-map-marker
          OpenStreetMap

      %li
        = link_to maps_path format: :json, tag: @orga.name do
          %em.fa.fa-li.fa-dot-circle-o
          GeoJSON

    - if user_signed_in?
      %h1
        %em.fa.fa-wrench
        = t '.actions'
      %h2
        = link_to edit_orga_path @orga do
          %em.fa.fa-lg.fa-pencil
          = t '.edit'
      %h2
        = link_to cancel_orga_path @orga do
          %em.fa.fa-lg.fa-thumbs-down
          = t '.cancel'

%dl
  - if @orga.city.present?
    %dt
      %em.fa.fa-compress
      = Orga.human_attribute_name :city
    %dd= @orga.city
  - if @orga.department.present?
    %dt= Orga.human_attribute_name :department
    %dd= @orga.department
  - if @orga.region.present?
    %dt
      %em.fa.fa-shield
      = Orga.human_attribute_name :region
    %dd= @orga.region
  - if @orga.url.present?
    %dt
      %em.fa.fa-external-link
      = Orga.human_attribute_name :url
    %dd= link_to @orga.url, @orga.url
  - if @orga.feed.present?
    %dt
      %em.fa.fa-rss
      = Orga.human_attribute_name :feed
    %dd= link_to @orga.feed, @orga.feed
  - if @orga.contact.present?
    %dt
      %em.fa.fa-envelope
      = Event.human_attribute_name :contact
    %dd= mail_to @orga.contact, nil,
      encode: (request.format == 'text/html' ? :javascript : nil),
      replace_at: ' CHEZ ', replace_dot: ' POINT '

  - if @events_future && @events_future.any?
    %dt= t '.future'
    %dd= t '.count', count: @events_future.count
  - if @events_future && @events_past.any?
    %dt= t '.past'
    %dd= t '.count', count: @events_past.count

.events#map{ title: @orga.name_as_tag,
  data: { url: maps_path(format: :json, tag: @orga.name_as_tag,
    future: false) } }

app/views/orgas/show.text.haml
=====================================================
#{Orga.human_attribute_name(:kind).concat(':').ljust 12       } #{@orga.kind.name}
#{Orga.human_attribute_name(:name).concat(':').ljust 12       } #{@orga.name}
#{Orga.human_attribute_name(:region).concat(':').ljust 12     } #{@orga.region}
#{Orga.human_attribute_name(:url).concat(':').ljust 12        } #{@orga.url}
#{Orga.human_attribute_name(:feed).concat(':').ljust 12       } #{@orga.feed}
#{Orga.human_attribute_name(:contact).concat(':').ljust 12    } #{@orga.contact}
#{Orga.human_attribute_name(:submitter).concat(':').ljust 12  } #{@orga.submitter}
=====================================================

app/views/orgas/validate.html.haml
%h2
  %em.fa.fa-exclamation-triangle
  = t '.title'

= form_for @orga, url: { action: :accept }, html: { method: :put } do |f|
  = link_to moderations_path do
    %em.fa.fa-arrow-left
    = t '.ko'

  = f.button do
    %em.fa.fa-thumbs-up
    = t '.ok'

%fieldset
  %legend
    %em.fa.fa-calendar
    = Orga.model_name.human
  = render file: '/orgas/show'